wget -x https://www.samara.com/
wget -x https://www.samara.com/assets/fonts/regola-book.woff2
wget -x https://www.samara.com/assets/fonts/regola-light.woff2
wget -x https://www.samara.com/assets/stylesheets/index.css
wget -x https://www.samara.com/assets/javascripts/trackers.js
wget -x https://www.samara.com/assets/javascripts/index.js
wget -x https://www.samara.com/assets/javascripts/contact/bundle.js
wget -x https://www.samara.com/assets/images/backyard/hero-xl-10-sky/hero-xl-10-sky-2880.webp
wget -x https://www.samara.com/assets/images/backyard/hero-xl-10-title.svg
wget -x https://www.samara.com/assets/images/backyard/hero-xl-10/hero-xl-10-2880.webp
wget -x https://www.samara.com/assets/images/backyard/intro-studio/intro-studio-800.webp
wget -x https://www.samara.com/assets/images/backyard/intro-twobed-white/intro-twobed-white-800.webp
wget -x https://www.samara.com/assets/images/backyard/intro-xl/intro-xl-800.webp
wget -x https://www.samara.com/assets/images/backyard/intro-twobed/intro-twobed-800.webp
wget -x https://www.samara.com/assets/images/backyard/intro-xl-green/intro-xl-green-800.webp
wget -x https://www.samara.com/assets/images/backyard/two-bedroom-hero/two-bedroom-hero-3000.jpg
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/12de6a2d9ca66bc16c9759870bc03a9e/thumbnails/thumbnail.jpg?width=600
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/7a56fe0435899af672fe98f8a7368074/thumbnails/thumbnail.jpg?width=1200
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/a740225302b2fed9096b40fff9363db9/thumbnails/thumbnail.jpg?width=400
wget -x https://www.samara.com/assets/images/insights/kurodas-thumbnail/kurodas-thumbnail-150.webp
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/003c536adcae09a8bd60466dd36e3582/thumbnails/thumbnail.jpg?width=400
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/acec9f3bb8f9e288a93705aadf70bb99/thumbnails/thumbnail.jpg?width=400
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/2c14b9c57ee6ce023bf6264c94d01689/thumbnails/thumbnail.jpg?width=400
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/10d8c1d596a292ae1725e63a39fca76b/thumbnails/thumbnail.jpg?width=400
wget -x https://www.samara.com/assets/images/backyard/1505/__studio/__studio-2880.webp
wget -x https://www.samara.com/assets/images/backyard/1505/__onebed/__onebed-2880.webp
wget -x https://www.samara.com/assets/images/backyard/1505/__twobed/__twobed-2880.webp
wget -x https://www.samara.com/assets/images/backyard/1505/__xl-10/__xl-10-2880.webp
wget -x https://www.samara.com/assets/images/backyard/1505/__xl/__xl-2880.webp
wget -x https://www.samara.com/assets/images/backyard/interior-xl-10/interior-xl-10-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/interior-carousel-xl-kitchen/interior-carousel-xl-kitchen-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/interior-carousel-xl-bathroom-left/interior-carousel-xl-bathroom-left-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/interior-carousel-xl-bathroom-right/interior-carousel-xl-bathroom-right-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/interior-carousel-xl-living-room-two/interior-carousel-xl-living-room-two-2000.jpg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/fonts/regola-regular.woff2
wget -x https://www.samara.com/assets/images/logo.svg
wget -x https://www.samara.com/assets/images/icons/chevron-mini-grey.svg
wget -x https://www.samara.com/assets/images/backyard/banner-showroom/banner-showroom-1440.webp
wget -x https://www.samara.com/assets/images/backyard/hollywood/hollywood-3000.jpg
wget -x https://www.samara.com/assets/images/backyard/green/green-3000.jpg
wget -x https://www.samara.com/assets/images/backyard/xl-carousel/xl-carousel-3000.jpg
wget -x https://www.samara.com/assets/images/backyard/intro-carousel-xl-10/intro-carousel-xl-10-3000.jpg
wget -x https://www.samara.com/assets/javascripts/vendor/three.js
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/backyard/models.data
wget -x https://www.samara.com/backyard.data
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/models-index-collage-one/models-index-collage-one-2000.webp
wget -x https://www.samara.com/assets/images/backyard/models/models-index-collage-two/models-index-collage-two-1000.webp
wget -x https://www.samara.com/assets/images/backyard/models/models-index-xl-10/models-index-xl-10-1000.webp
wget -x https://www.samara.com/assets/images/backyard/models/models-index-xl-8/models-index-xl-8-1000.webp
wget -x https://www.samara.com/assets/images/backyard/models/models-index-twobed/models-index-twobed-1000.webp
wget -x https://www.samara.com/assets/images/backyard/models/models-index-onebed/models-index-onebed-1000.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/backyard/models/models-index-studio/models-index-studio-1000.webp
wget -x https://www.samara.com/backyard/studio.data
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/hero-studio-horizontal/hero-studio-horizontal-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-hero-studio/interior-hero-studio-3000.webp
wget -x https://www.samara.com/assets/images/backyard/kitchen-studio/kitchen-studio-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/corridor-studio/corridor-studio-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-studio-hallway/interior-studio-hallway-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/bathroom/bathroom-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-studio-five/interior-carousel-studio-five-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/faq-up.svg
wget -x https://www.samara.com/assets/images/backyard/models/intro-studio/intro-studio-1200.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/backyard/models/studio-floorplan-horizontal/studio-floorplan-horizontal-2000.webp
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-right.svg
wget -x https://www.samara.com/assets/images/icons/download-blue.svg
wget -x https://www.samara.com/assets/images/backyard/models/collage-studio-one/collage-studio-one-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-studio-two/collage-studio-two-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-studio-three/collage-studio-three-1400.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/doorway-onebed/doorway-onebed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-twobed/doorway-twobed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-xl/doorway-xl-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/specs-studio/specs-studio-2880.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/showrooms.data
wget -x https://www.samara.com/backyard/studio
wget -x https://www.samara.com/backyard/one-bedroom.data
wget -x https://www.samara.com/assets/images/backyard/bathroom/bathroom-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/faq-up.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/hero-onebed-horizontal/hero-onebed-horizontal-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-hero-onebed/interior-hero-onebed-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-onebed-one/interior-carousel-onebed-one-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-onebed-two/interior-carousel-onebed-two-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-onebed-three/interior-carousel-onebed-three-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-onebed-four/interior-carousel-onebed-four-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/intro-onebed/intro-onebed-1200.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/backyard/configure.data
wget -x https://www.samara.com/assets/images/favicons/icon64x.png
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/models/onebed-floorplan-horizontal/onebed-floorplan-horizontal-2000.webp
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-right.svg
wget -x https://www.samara.com/assets/images/icons/download-blue.svg
wget -x https://www.samara.com/assets/images/backyard/models/collage-onebed-two/collage-onebed-two-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-onebed-one/collage-onebed-one-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-onebed-three/collage-onebed-three-1400.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/doorway-onebed/doorway-onebed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-twobed/doorway-twobed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-studio/doorway-studio-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/specs-onebed/specs-onebed-2880.webp
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/backyard/financing.data
wget -x https://www.samara.com/backyard/two-bedroom.data
wget -x https://www.samara.com/assets/images/backyard/bathroom/bathroom-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/faq-up.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/hero-twobed-horizontal/hero-twobed-horizontal-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-hero-twobed/interior-hero-twobed-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-twobed-one/interior-carousel-twobed-one-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-twobed-two/interior-carousel-twobed-two-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-twobed-three/interior-carousel-twobed-three-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-studio-five/interior-carousel-studio-five-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/intro-twobed/intro-twobed-1200.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/models/twobed-floorplan-horizontal/twobed-floorplan-horizontal-2000.webp
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-right.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/icons/download-blue.svg
wget -x https://www.samara.com/assets/images/backyard/models/collage-twobed-two/collage-twobed-two-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-twobed-one/collage-twobed-one-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-twobed-three/collage-twobed-three-1400.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/doorway-studio/doorway-studio-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-onebed/doorway-onebed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-xl/doorway-xl-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/specs-twobed/specs-twobed-2880.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/backyard/xl-8.data
wget -x https://www.samara.com/assets/images/backyard/faq-up.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/hero-xl-horizontal/hero-xl-horizontal-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-hero-xl/interior-hero-xl-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-one/interior-carousel-xl-one-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-two/interior-carousel-xl-two-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-three/interior-carousel-xl-three-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-four/interior-carousel-xl-four-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-five/interior-carousel-xl-five-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-six/interior-carousel-xl-six-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-seven/interior-carousel-xl-seven-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/intro-xl/intro-xl-1200.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/backyard/models/xl-floorplan-horizontal/xl-floorplan-horizontal-2000.webp
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-right.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-one/collage-xl-one-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-two/collage-xl-two-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-three/collage-xl-three-1400.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/doorway-onebed/doorway-onebed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-twobed/doorway-twobed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-xl-10/doorway-xl-10-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/specs-xl/specs-xl-2880.webp
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/backyard/xl-10.data
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-seven/interior-carousel-xl-seven-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/faq-up.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/hero-xl-10/hero-xl-10-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-hero-xl-10/interior-hero-xl-10-3000.webp
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-10-one/interior-carousel-xl-10-one-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-10-two/interior-carousel-xl-10-two-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-10-three/interior-carousel-xl-10-three-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-10-four/interior-carousel-xl-10-four-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/interior-carousel-xl-10-five/interior-carousel-xl-10-five-2000.jpg
wget -x https://www.samara.com/assets/images/backyard/models/intro-xl-10/intro-xl-10-1200.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/backyard/models/xl-10-floorplan-horizontal/xl-10-floorplan-horizontal-2000.webp
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-right.svg
wget -x https://www.samara.com/assets/images/backyard/dimension-arrow-top.svg
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-10-two/collage-xl-10-two-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-10-one/collage-xl-10-one-1400.webp
wget -x https://www.samara.com/assets/images/backyard/models/collage-xl-10-three/collage-xl-10-three-1400.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/backyard/models/doorway-onebed/doorway-onebed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-twobed/doorway-twobed-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/doorway-xl/doorway-xl-720.webp
wget -x https://www.samara.com/assets/images/backyard/models/specs-xl-10/specs-xl-10-2880.webp
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/backyard/how-it-works.data
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/3d4770770f6df326b85a0144ec05de32/thumbnails/thumbnail.jpg?width=1440
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/e862d0887018ec8ad0704988bb5081cd/thumbnails/thumbnail.jpg?width=600
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/35c205a566408f2f086a75dc7b70dc6a/thumbnails/thumbnail.jpg?width=1440
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/7e210d2c89a48e4d9ff1e853c07f76c5/thumbnails/thumbnail.jpg?width=600
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/95033dd9380338714fd769eb6861d893/thumbnails/thumbnail.jpg?width=600
wget -x https://www.samara.com/assets/images/insights/kurodas-thumbnail/kurodas-thumbnail-150.webp
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/how-it-works/how-it-works-step-1/how-it-works-step-1-1440.webp
wget -x https://www.samara.com/assets/images/how-it-works/how-it-works-step-2/how-it-works-step-2-1440.webp
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/3d4770770f6df326b85a0144ec05de32/downloads/default.mp4
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/3d4770770f6df326b85a0144ec05de32/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6IjNkNDc3MDc3MGY2ZGYzMjZiODVhMDE0NGVjMDVkZTMyIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6NDcuMjAwMDAwNzYyLCJyZXNvbHV0aW9uIjoiMTA4MCIsInRvdGFsQnl0ZVNpemUiOjI2NjcxNjM1fQ&s=wqDCowVtw5IkDX3Ctk3Cl8Ojw65Zw7PDmXvDggVXUUs_KGtZw5LCmUbCh1HDtQ
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/e862d0887018ec8ad0704988bb5081cd/downloads/default.mp4
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/e862d0887018ec8ad0704988bb5081cd/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6ImU4NjJkMDg4NzAxOGVjOGFkMDcwNDk4OGJiNTA4MWNkIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MTUsInJlc29sdXRpb24iOiI0ODAiLCJ0b3RhbEJ5dGVTaXplIjoyMDIyMjg5fQ&s=w6_CucKmODI2AcOqwp_DixVlDcK8wrvCtMOgT8OCwr_DrMOhVk_DtjZ5HR0_w6PCpQ
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/e862d0887018ec8ad0704988bb5081cd/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6ImU4NjJkMDg4NzAxOGVjOGFkMDcwNDk4OGJiNTA4MWNkIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MTUsInJlc29sdXRpb24iOiI0ODAiLCJ0b3RhbEJ5dGVTaXplIjoyMDIyMjg5fQ&s=w6_CucKmODI2AcOqwp_DixVlDcK8wrvCtMOgT8OCwr_DrMOhVk_DtjZ5HR0_w6PCpQ
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/35c205a566408f2f086a75dc7b70dc6a/downloads/default.mp4
wget -x https://www.samara.com/assets/images/how-it-works/how-it-works-step-6/how-it-works-step-6-1440.webp
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/35c205a566408f2f086a75dc7b70dc6a/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6IjM1YzIwNWE1NjY0MDhmMmYwODZhNzVkYzdiNzBkYzZhIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6NjEuODk5OTk5OTc2LCJyZXNvbHV0aW9uIjoiMTA4MCIsInRvdGFsQnl0ZVNpemUiOjE5OTMyMDM3fQ&s=NsKSVMOxw7BLwph7wpg3UDJVbcKEwqdGw7vDkCYSccKAw4QYwrPDsWMMw43DiCY
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/35c205a566408f2f086a75dc7b70dc6a/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6IjM1YzIwNWE1NjY0MDhmMmYwODZhNzVkYzdiNzBkYzZhIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6NjEuODk5OTk5OTc2LCJyZXNvbHV0aW9uIjoiMTA4MCIsInRvdGFsQnl0ZVNpemUiOjE5OTMyMDM3fQ&s=NsKSVMOxw7BLwph7wpg3UDJVbcKEwqdGw7vDkCYSccKAw4QYwrPDsWMMw43DiCY
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/7e210d2c89a48e4d9ff1e853c07f76c5/downloads/default.mp4
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/7e210d2c89a48e4d9ff1e853c07f76c5/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6IjdlMjEwZDJjODlhNDhlNGQ5ZmYxZTg1M2MwN2Y3NmM1Iiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MjIuMjAwMDAwNzYyLCJyZXNvbHV0aW9uIjoiNDgwIiwidG90YWxCeXRlU2l6ZSI6MTcwMjg4NX0&s=VlUJY8OhG8OrwoUNYsKTw5vDi8OYw4kSUsOkYH_DnsKyUR0wKMOMDcOlAMOPw6Q
wget -x https://www.samara.com/assets/images/how-it-works/liftoff.svg
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/95033dd9380338714fd769eb6861d893/downloads/default.mp4
wget -x https://www.samara.com/assets/images/how-it-works/how-it-works-step-9/how-it-works-step-9-1440.webp
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/95033dd9380338714fd769eb6861d893/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6Ijk1MDMzZGQ5MzgwMzM4NzE0ZmQ3NjllYjY4NjFkODkzIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MzYuNDAwMDAxNTI1LCJyZXNvbHV0aW9uIjoiMTA4MCIsInRvdGFsQnl0ZVNpemUiOjIyMTQ2MjUxfQ&s=P8O0aQ7CulcJw7XDhWp8w6N6w4wFwqDCvsKFEyx5QMKVfnEgJMOGEVxIwpg
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/7e210d2c89a48e4d9ff1e853c07f76c5/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6IjdlMjEwZDJjODlhNDhlNGQ5ZmYxZTg1M2MwN2Y3NmM1Iiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MjIuMjAwMDAwNzYyLCJyZXNvbHV0aW9uIjoiNDgwIiwidG90YWxCeXRlU2l6ZSI6MTcwMjg4NX0&s=VlUJY8OhG8OrwoUNYsKTw5vDi8OYw4kSUsOkYH_DnsKyUR0wKMOMDcOlAMOPw6Q
wget -x https://www.samara.com/assets/images/how-it-works/welcome/welcome-2880.webp
wget -x https://www.samara.com/assets/images/how-it-works/liftoff.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/how-it-works/welcome/welcome-2880.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/insights/how-we-built-a-fire-resistant-ADU.data
wget -x https://customer-rzhtf894oui3z1e3.cloudflarestream.com/95033dd9380338714fd769eb6861d893/dl/default.mp4?p=eyJ0eXBlIjoiZG93bmxvYWRzIiwidmlkZW9JRCI6Ijk1MDMzZGQ5MzgwMzM4NzE0ZmQ3NjllYjY4NjFkODkzIiwib3duZXJJRCI6NDU4NjQ0NjksImNyZWF0b3JJRCI6IiIsImRvd25sb2FkVHlwZSI6ImRlZmF1bHQiLCJzdG9yYWdlUHJvdmlkZXIiOjQsImR1cmF0aW9uU2VjcyI6MzYuNDAwMDAxNTI1LCJyZXNvbHV0aW9uIjoiMTA4MCIsInRvdGFsQnl0ZVNpemUiOjIyMTQ2MjUxfQ&s=P8O0aQ7CulcJw7XDhWp8w6N6w4wFwqDCvsKFEyx5QMKVfnEgJMOGEVxIwpg
wget -x https://www.samara.com/assets/images/icons/arrow-right-blue.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/financing/financing-main/financing-main-1000.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-01/financing-rate-benefits-01-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-02/financing-rate-benefits-02-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-03/financing-rate-benefits-03-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-04/financing-rate-benefits-04-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-05/financing-rate-benefits-05-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-06/financing-rate-benefits-06-500.webp
wget -x https://www.samara.com/assets/images/icons/xmark-grey.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-grey.svg
wget -x https://www.samara.com/assets/stylesheets/financing/bundle.css
wget -x https://www.samara.com/assets/javascripts/financing/bundle.js
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-03/financing-rate-benefits-03-500.webp
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-06/financing-rate-benefits-06-500.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-blue.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/showroom/hero-01/hero-01-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/hero-02/hero-02-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/redwood-city/redwood-city-1080.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/showroom/hero-03/hero-03-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/thousand-oaks/thousand-oaks-1080.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/showroom/redwood-city/redwood-city-1080.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-blue.svg
wget -x https://www.samara.com/insights.data
wget -x https://www.samara.com/news.data
wget -x https://www.samara.com/jobs.data
wget -x https://www.samara.com/assets/images/newsroom/fastcompany.svg
wget -x https://www.samara.com/assets/images/newsroom/bloomberg.svg
wget -x https://www.samara.com/assets/images/newsroom/wsj.svg
wget -x https://www.samara.com/assets/images/newsroom/wallpaper.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/newsroom/adu-valley/adu-valley-2880.webp
wget -x https://www.samara.com/assets/images/newsroom/adu-valley-portrait/adu-valley-portrait-1125.webp
wget -x https://www.samara.com/assets/images/newsroom/cnbc.svg
wget -x https://www.samara.com/assets/remote/7e59efa2-59ea-4288-8dea-05bb7cdfb800/w=2200
wget -x https://www.samara.com/assets/remote/024a83bb-ea38-40e8-7b6e-5fdd097a5c00/w=2200
wget -x https://www.samara.com/assets/images/icons/box-video-light-grey.svg
wget -x https://www.samara.com/assets/images/icons/box-out-light-grey.svg
wget -x https://www.samara.com/assets/remote/7ce5f94c-fc2b-4c3b-339c-24e283c18e00/w=2200
wget -x https://www.samara.com/assets/remote/b1ae142b-b246-4501-20f1-f1350a84c300/w=2200
wget -x https://www.samara.com/assets/remote/c5700752-823e-4522-f805-a3a788b63400/w=2200
wget -x https://www.samara.com/assets/remote/4f02d289-169f-4ab4-50e7-edb29cfa4300/w=2200
wget -x https://www.samara.com/assets/remote/dd6932ff-e29e-410b-b2e6-4f23130e1e00/w=2200
wget -x https://www.samara.com/assets/remote/59ee21f7-d5a4-4592-e873-b16c86b7ea00/w=2200
wget -x https://www.samara.com/assets/remote/18a8fd12-a34d-4b25-ee57-9d6aab3b7700/w=2200
wget -x https://www.samara.com/assets/remote/d232879b-2c44-458d-f18f-abf491e85200/w=2200
wget -x https://www.samara.com/assets/fonts/regola-medium.woff2
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/news/time-names-backyard-a-best-invention-of-2024.data
wget -x https://www.samara.com/assets/remote/7e59efa2-59ea-4288-8dea-05bb7cdfb800/w=2200
wget -x https://www.samara.com/news/samara-launches-proprietary-financing-product-to-bring-more-space-to-millions-of-homeowners.data
wget -x https://www.samara.com/assets/remote/c5700752-823e-4522-f805-a3a788b63400/w=2200
wget -x https://www.samara.com/news/samara-acquires-factory-to-scale-manufacturing-of-backyard.data
wget -x https://www.samara.com/assets/remote/dd6932ff-e29e-410b-b2e6-4f23130e1e00/w=2200
wget -x https://www.samara.com/news/samara-raises-41-million-to-bring-high-quality-adus-to-every-backyard-in-california-and-beyond.data
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/remote/18a8fd12-a34d-4b25-ee57-9d6aab3b7700/w=2200
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/remote/93578295-abea-42a3-500e-969069e49200/w=400
wget -x https://www.samara.com/assets/remote/2b76073a-ab8d-4488-6ebc-af6a19c92700/w=400
wget -x https://www.samara.com/assets/remote/7b4af13f-4e79-4bc5-81c9-8e245b224e00/w=400
wget -x https://www.samara.com/assets/remote/8a85faee-0714-4c7c-eb3c-712f65391800/w=400
wget -x https://www.samara.com/assets/remote/7fd63db2-b177-45ea-299d-1dd0804d2d00/w=400
wget -x https://www.samara.com/assets/remote/e96ecaec-e24a-42e1-5f4f-f02dc7047100/w=400
wget -x https://www.samara.com/assets/remote/5950ca62-25e8-4ea9-488b-844703a74000/w=1600
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/insights/life-with-backyard-meet-the-kurodas.data
wget -x https://www.samara.com/assets/images/insights/04-kuroda/04-kuroda-2880.webp
wget -x https://www.samara.com/insights/report-adus-win-over-california-homeowners.data
wget -x https://www.samara.com/assets/remote/5950ca62-25e8-4ea9-488b-844703a74000/w=1600
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-blue.svg
wget -x https://www.samara.com/assets/images/showroom/hero-01/hero-01-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/hero-02/hero-02-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/redwood-city/redwood-city-1080.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/showroom/hero-03/hero-03-2880.jpg
wget -x https://www.samara.com/assets/images/showroom/thousand-oaks/thousand-oaks-1080.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/showroom/thousand-oaks/thousand-oaks-1080.webp
wget -x https://www.samara.com/developers.data
wget -x https://www.samara.com/backyard/faq.data
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/multiunit/logo-backyard.svg
wget -x https://www.samara.com/assets/images/multiunit/hero/hero-2880.webp
wget -x https://www.samara.com/assets/images/multiunit/community/community-2880.webp
wget -x https://www.samara.com/assets/stylesheets/multiunit/bundle.css
wget -x https://www.samara.com/assets/javascripts/multiunit/bundle.js
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/multiunit/hero/hero-2880.webp
wget -x https://www.samara.com/assets/images/multiunit/hero/hero-2880.webp
wget -x https://www.samara.com/assets/images/multiunit/community/community-2880.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/multiunit/community/community-2880.webp
wget -x https://www.samara.com/assets/images/financing/financing-main/financing-main-1000.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-blue.svg
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-01/financing-rate-benefits-01-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-02/financing-rate-benefits-02-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-04/financing-rate-benefits-04-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-05/financing-rate-benefits-05-500.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/icons/xmark-grey.svg
wget -x https://www.samara.com/assets/images/icons/checkmark-grey.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-03/financing-rate-benefits-03-500.webp
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-06/financing-rate-benefits-06-500.webp
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/financing/financing-rate-benefits-02/financing-rate-benefits-02-500.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/doorway/showroom-landscape/showroom-landscape-720.webp
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://www.samara.com/assets/images/doorway/multiunit-landscape/multiunit-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/configure-landscape/configure-landscape-720.webp
wget -x https://www.samara.com/assets/images/doorway/doorway-fire-resistant/doorway-fire-resistant-720.webp
wget -x https://www.samara.com/backyard/guides.data
wget -x https://www.samara.com/assets/images/icons/chevron-white.svgwget -x https://www.samara.com/assets/images/bullet.svg
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/icons/checkmark-white.svg
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/icons/chevron-white.svg
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/stylesheets/configurator/bundle.css
wget -x https://www.samara.com/assets/javascripts/configurator/bundle/index.js
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/javascripts/configurator/bundle/index-CYB3rl_7.js
wget -x https://www.samara.com/assets/images/icons/arrow-right-white.svg
wget -x https://www.samara.com/assets/images/configure/drag.svg
wget -x https://www.samara.com/assets/images/configure/silver-coarse.png
wget -x https://www.samara.com/assets/images/configure/floor-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-bone-white.jpg
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-natural-oak.jpg
wget -x https://mailer.samara.com/api/order/create
wget -x https://www.samara.com/assets/ddd/models/samara/1B.glb
wget -x https://www.samara.com/assets/ddd/textures/hdr/hdr-2
wget -x https://www.samara.com/assets/ddd/textures/Wood_basecolor.png
wget -x https://www.samara.com/assets/ddd/textures/Wood_normal.png
wget -x https://www.samara.com/assets/ddd/textures/Metal_basecolor.png
wget -x https://www.samara.com/assets/ddd/textures/Metal_normal.png
wget -x https://www.samara.com/assets/ddd/textures/grid_solar_panel_tiled_basecolor_dark.jpg
wget -x https://www.samara.com/assets/ddd/textures/grid_solar_panel_tiled_metallic.jpg
wget -x https://www.samara.com/assets/ddd/textures/Support/Deck_2K.png
wget -x https://www.samara.com/assets/ddd/textures/Support/SupportPatio_2K.png
wget -x https://www.samara.com/assets/ddd/textures/AO_AirEx.png
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Chair_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Bath_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Faucet_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Oven_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Shelves_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Wood_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Lamp_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Sofa_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Bed_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Air_purification.jpg
wget -x https://www.samara.com/assets/ddd/textures/Oak_Wood_Varnished_Albedo_2Kt.jpg
wget -x https://www.samara.com/assets/ddd/textures/glass_orm.png
wget -x https://www.samara.com/assets/ddd/textures/AO_channels.png
wget -x https://www.samara.com/assets/ddd/textures/Tesla_BaseColor.webp
wget -x https://www.samara.com/assets/ddd/textures/Tesla_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/TeslaFloor_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/TeslaWall_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/Wall_i_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Wood_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Floor_1B.png
wget -x https://www.samara.com/assets/ddd/textures/1_1B.png
wget -x https://www.samara.com/assets/ddd/textures/2_1B.png
wget -x https://www.samara.com/assets/ddd/textures/3_1B.png
wget -x https://www.samara.com/assets/ddd/textures/4_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Wall_e_1B_2.webp
wget -x https://www.samara.com/assets/ddd/textures/Wall_e_1B_1.webp
wget -x https://www.samara.com/assets/ddd/textures/AO_RoofSolarFull%20-%20no%20cables.png
wget -x https://www.samara.com/assets/ddd/textures/AO_RoofSolarOne%20-%20no%20cables.png
wget -x https://www.samara.com/assets/ddd/textures/AO_1BedRoof_SolarClean_1K.png
wget -x https://www.samara.com/assets/images/favicons/favicon.png
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-bone-white.jpg
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/silver-coarse.png
wget -x https://www.samara.com/assets/images/configure/interior/floor-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/interior/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/interior/floor-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/interior/floor-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_nat_table.jpg
wget -x https://www.samara.com/assets/images/configure/interior/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/floor-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/floor-dark-stained-oak.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_nat_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_nat_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_nat_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_nat_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_nat_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_nat_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_nat_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_white_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_nat_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_dark_white_island.jpg
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-natural-oak.jpg
wget -x https://www.samara.com/assets/images/configure/kitchen-cabinet-finish-bone-white.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_island.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_table.jpg
wget -x https://www.samara.com/assets/images/configure/1505/kitchen_xl10_nat_white_island.jpg
wget -x https://www.samara.com/assets/ddd/models/samara/1B.glb
wget -x https://www.samara.com/assets/ddd/textures/hdr/hdr-2
wget -x https://www.samara.com/assets/ddd/textures/Wood_basecolor.png
wget -x https://www.samara.com/assets/ddd/textures/Wood_normal.png
wget -x https://www.samara.com/assets/ddd/textures/Metal_basecolor.png
wget -x https://www.samara.com/assets/ddd/textures/Metal_normal.png
wget -x https://www.samara.com/assets/ddd/textures/grid_solar_panel_tiled_basecolor_dark.jpg
wget -x https://www.samara.com/assets/ddd/textures/grid_solar_panel_tiled_metallic.jpg
wget -x https://www.samara.com/assets/ddd/textures/Support/Deck_2K.png
wget -x https://www.samara.com/assets/ddd/textures/Support/SupportPatio_2K.png
wget -x https://www.samara.com/assets/ddd/textures/AO_AirEx.png
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Chair_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Bath_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Faucet_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Oven_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Shelves_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Wood_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Lamp_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Sofa_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Albedo_Bed_512.jpg
wget -x https://www.samara.com/assets/ddd/textures/Air_purification.jpg
wget -x https://www.samara.com/assets/ddd/textures/Oak_Wood_Varnished_Albedo_2Kt.jpg
wget -x https://www.samara.com/assets/ddd/textures/glass_orm.png
wget -x https://www.samara.com/assets/ddd/textures/AO_channels.png
wget -x https://www.samara.com/assets/ddd/textures/Tesla_BaseColor.webp
wget -x https://www.samara.com/assets/ddd/textures/Tesla_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/TeslaFloor_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/TeslaWall_AO.webp
wget -x https://www.samara.com/assets/ddd/textures/Wall_i_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Wood_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Floor_1B.png
wget -x https://www.samara.com/assets/ddd/textures/1_1B.png
wget -x https://www.samara.com/assets/ddd/textures/2_1B.png
wget -x https://www.samara.com/assets/ddd/textures/3_1B.png
wget -x https://www.samara.com/assets/ddd/textures/4_1B.png
wget -x https://www.samara.com/assets/ddd/textures/Wall_e_1B_2.webp
wget -x https://www.samara.com/assets/ddd/textures/Wall_e_1B_1.webp
wget -x https://www.samara.com/assets/ddd/textures/AO_RoofSolarFull%20-%20no%20cables.png
wget -x https://www.samara.com/assets/ddd/textures/AO_RoofSolarOne%20-%20no%20cables.png
wget -x https://www.samara.com/assets/ddd/textures/AO_1BedRoof_SolarClean_1K.png
wget -x https://www.samara.com/assets/images/configure/interior/roller-blinds.webp
wget -x https://www.samara.com/assets/images/configure/interior/no-blinds.webp
wget -x https://www.samara.com/assets/images/icons/checkmark-grey.svg
wget -x https://www.samara.com/assets/images/icons/arrow-right-black.svg
wget -x https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css
wget -x https://www.samara.com/assets/javascripts/configurator/bundle/mapbox-gl-Di4qNU7a.js